openapi: 3.1.0
info:
  title: EventraAI API
  version: 1.0.0
paths:
  /api/events:
    get:
      summary: Get all events for the authenticated user
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        status:
          type: string
